const { Client } = require('pg');

const connectionString = "postgresql://postgres.fjljkiwiobhbazzqusie:osWDtHrdSWQ96Z29@aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres";

async function createTable() {
    const client = new Client({
        connectionString: connectionString,
        ssl: { rejectUnauthorized: false }
    });

    try {
        await client.connect();
        console.log('🔌 Connected to database. Creating table...');

        const query = `
            CREATE TABLE IF NOT EXISTS sensor_logs (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                temp REAL,
                humi REAL,
                ec INTEGER,
                ph REAL,
                n INTEGER,
                p INTEGER,
                k INTEGER
            );
        `;

        await client.query(query);
        console.log('✅ Table "sensor_readings" created successfully.');
    } catch (err) {
        console.error('❌ Error creating table:', err);
    } finally {
        await client.end();
    }
}

createTable();
