-- Drop all old tables
DROP TABLE IF EXISTS "SensorLogs" CASCADE;
DROP TABLE IF EXISTS "Sensors" CASCADE;
DROP TABLE IF EXISTS "Devices" CASCADE;
DROP TABLE IF EXISTS "Alerts" CASCADE;
DROP TABLE IF EXISTS "SensorLogData" CASCADE;
DROP TABLE IF EXISTS "__EFMigrationsHistory" CASCADE;
